name: Lab2 CI/CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: docker compose up -d

      - name: Check start of services
        run: |
          chmod +x ./scripts/wait-script.sh
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

  integration-tests:
    name: Run integration tests
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: docker compose up -d

      - name: Wait for Spring Boot to start
        run: sleep 20s
        shell: bash

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/collection.json
          environment: postman/local-environment.json
          delayRequest: 1000
          reporters: '[ "cli" ]'

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v